modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="curse"
version="1.6.0"
displayName="Curse"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
credits="Jusey1, Burack"
authors="Jusey1"
description="Optional difficulty increasing mod on a per player basis"

[[dependencies.curse]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"



